/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GpxData {
  'stageId' : StageId,
  'blob' : ExternalBlob,
  'uploadedAt' : bigint,
}
export interface Photo {
  'id' : PhotoId,
  'elevation' : [] | [number],
  'stageId' : StageId,
  'blob' : ExternalBlob,
  'description' : string,
  'timestamp' : bigint,
  'uploadedBy' : Principal,
}
export type PhotoId = bigint;
export interface PhotoInput {
  'elevation' : [] | [number],
  'stageId' : StageId,
  'blob' : ExternalBlob,
  'description' : string,
}
export interface Stage {
  'id' : StageId,
  'ascentM' : bigint,
  'dateTo' : string,
  'endElevation' : bigint,
  'startElevation' : bigint,
  'taxiInfo' : [] | [TaxiInfo],
  'accommodation' : string,
  'estimatedTimeH' : number,
  'distanceKm' : number,
  'isGipfeltag' : boolean,
  'endLocation' : string,
  'number' : bigint,
  'dateFrom' : string,
  'startLocation' : string,
  'descentM' : bigint,
}
export type StageId = bigint;
export interface TaxiInfo {
  'departureLocation' : string,
  'departureTime' : string,
  'pricePerPerson' : string,
  'phone' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPhoto' : ActorMethod<[PhotoInput], Photo>,
  'deletePhoto' : ActorMethod<[PhotoId], boolean>,
  'getGpx' : ActorMethod<[StageId], [] | [GpxData]>,
  'getPhotos' : ActorMethod<[StageId], Array<Photo>>,
  'getStage' : ActorMethod<[StageId], [] | [Stage]>,
  'getStages' : ActorMethod<[], Array<Stage>>,
  'uploadGpx' : ActorMethod<[StageId, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];