/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StageId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoInput = IDL.Record({
  'elevation' : IDL.Opt(IDL.Nat),
  'stageId' : StageId,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
});
export const PhotoId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Photo = IDL.Record({
  'id' : PhotoId,
  'elevation' : IDL.Opt(IDL.Nat),
  'stageId' : StageId,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'uploadedBy' : IDL.Principal,
});
export const GpxData = IDL.Record({
  'stageId' : StageId,
  'blob' : ExternalBlob,
  'uploadedAt' : Timestamp,
});
export const TaxiInfo = IDL.Record({
  'departureLocation' : IDL.Text,
  'departureTime' : IDL.Text,
  'pricePerPerson' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const Stage = IDL.Record({
  'id' : StageId,
  'dateTo' : IDL.Text,
  'endElevation' : IDL.Nat,
  'startElevation' : IDL.Nat,
  'taxiInfo' : IDL.Opt(TaxiInfo),
  'accommodation' : IDL.Text,
  'estimatedTimeH' : IDL.Nat,
  'elevationLossM' : IDL.Nat,
  'distanceKm' : IDL.Nat,
  'isGipfeltag' : IDL.Bool,
  'endLocation' : IDL.Text,
  'elevationGainM' : IDL.Nat,
  'number' : IDL.Nat,
  'dateFrom' : IDL.Text,
  'startLocation' : IDL.Text,
  'highlight' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPhoto' : IDL.Func([PhotoInput], [Photo], []),
  'deletePhoto' : IDL.Func([PhotoId], [IDL.Bool], []),
  'getGpx' : IDL.Func(
      [StageId],
      [IDL.Variant({ 'ok' : GpxData, 'err' : IDL.Text })],
      ['query'],
    ),
  'getPhotos' : IDL.Func([StageId], [IDL.Vec(Photo)], ['query']),
  'getStage' : IDL.Func([StageId], [IDL.Opt(Stage)], ['query']),
  'getStages' : IDL.Func([], [IDL.Vec(Stage)], ['query']),
  'uploadGpx' : IDL.Func(
      [StageId, ExternalBlob],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StageId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoInput = IDL.Record({
    'elevation' : IDL.Opt(IDL.Nat),
    'stageId' : StageId,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
  });
  const PhotoId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Photo = IDL.Record({
    'id' : PhotoId,
    'elevation' : IDL.Opt(IDL.Nat),
    'stageId' : StageId,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'uploadedBy' : IDL.Principal,
  });
  const GpxData = IDL.Record({
    'stageId' : StageId,
    'blob' : ExternalBlob,
    'uploadedAt' : Timestamp,
  });
  const TaxiInfo = IDL.Record({
    'departureLocation' : IDL.Text,
    'departureTime' : IDL.Text,
    'pricePerPerson' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Stage = IDL.Record({
    'id' : StageId,
    'dateTo' : IDL.Text,
    'endElevation' : IDL.Nat,
    'startElevation' : IDL.Nat,
    'taxiInfo' : IDL.Opt(TaxiInfo),
    'accommodation' : IDL.Text,
    'estimatedTimeH' : IDL.Nat,
    'elevationLossM' : IDL.Nat,
    'distanceKm' : IDL.Nat,
    'isGipfeltag' : IDL.Bool,
    'endLocation' : IDL.Text,
    'elevationGainM' : IDL.Nat,
    'number' : IDL.Nat,
    'dateFrom' : IDL.Text,
    'startLocation' : IDL.Text,
    'highlight' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPhoto' : IDL.Func([PhotoInput], [Photo], []),
    'deletePhoto' : IDL.Func([PhotoId], [IDL.Bool], []),
    'getGpx' : IDL.Func(
        [StageId],
        [IDL.Variant({ 'ok' : GpxData, 'err' : IDL.Text })],
        ['query'],
      ),
    'getPhotos' : IDL.Func([StageId], [IDL.Vec(Photo)], ['query']),
    'getStage' : IDL.Func([StageId], [IDL.Opt(Stage)], ['query']),
    'getStages' : IDL.Func([], [IDL.Vec(Stage)], ['query']),
    'uploadGpx' : IDL.Func(
        [StageId, ExternalBlob],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };